### PR TITLE
Fix up formatter

### PR DESCRIPTION
**Pull request by wlonk**
Here's the cleanup.

### CODE REVIEW

**Comment by jkakar** [comment]
Thanks for the follow up, I appreciate it! It's been a long time since I touched this library and my local environment is no longer setup to publish a new version. I'll sort that out in the next few days and get a new version released.

**Comment by wlonk** [comment]
Just checking in on this; have you had a chance to publish a new version? Thanks!

**Comment by jkakar** [comment]
Hey @wlonk, sorry for the slow response... I looked into publishing a new version recently but was blocked on needing to upgrade the package setup. I haven't actually used Python much in the last 7 years, so would need to re-learn how to do that. Is this something you're interested in doing?

**Comment by wlonk** [comment]
Sure thing. What do we need to do to make that happen?

**Comment by jkakar** [comment]
Are you foxfour on PyPI? I can add you as a maintainer of logfmt so you can build and upload packages.

**Comment by wlonk** [comment]
I am! Thanks, I will do so once you add me.

**Comment by jkakar** [comment]
Thank you! That's done. Also, if you're interested, I'd be happy for you to fork this project and take over ownership of the PyPI package. For now, I made you a maintainer on PyPI.

**Comment by wlonk** [comment]
Thanks. I'll take a look tonight or tomorrow and get back to you.

**Comment by wlonk** [comment]
Cool. I just uploaded v0.4.0 to PyPI, and pushed the source and tagged that to my fork (https://github.com/wlonk/logfmt-python/releases/tag/v0.4.0)

I might do a little documentation clean up, including describing (and tweaking) the build and publish process, and if you're cool with it I'll change PyPI to point to my fork.

**Comment by jkakar** [comment]
100% cool with it! Thank you! I'll update the README here to point to your fork, too.

**Comment by jkakar** [comment]
Okay, the README now points to your fork. Let me know if you'd prefer I redact that statement from the README, but I guess you're cool with it. :)

**Pull request merged**
