### PR TITLE
Add format function to package

### PR DESCRIPTION
**Pull request by gtrevg**
Rather than having every python developer have to properly format their log data with custom formatting code, this logfmt-python project can be imported and used.  If the library gets updates in speed/bug fixes, etc, then the whole community will benefit.

Thanks

### CODE REVIEW

**Comment by luxflux** [comment]
Would be nice to see this merged... What can we do to merge it?

**Comment by jkakar** [comment]
@luxflux Hey, sorry for the slow response on this pull request.  We need to fix the tests and merge master forward.  I can try to get to that in the coming week or so, but if you beat me to it, all the better. :)

**Comment by ycheng517** [comment]
@jkakar would it still be possible for this PR to be merged?

**Comment by jkakar** [comment]
Thanks for the reminder @ycheng517! I'd completely forgotten about the changes that @gtrevg was kind enough to share. I've fixed conflicts and merged these changes in #7.

**Pull request closed without merging**
